markdown: kramdown
permalink: /:categories/:title/
productionUrl: https://www.simple.gy
host: 0.0.0.0 # allows external access
defaults:
  -
    scope:
      path: "projects"
      type: "posts"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Eric Miller"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

exclude: ['*.sass', '/Gemfile*', '/README.md' ]


# Github allows changing:
github: [metadata]
kramdown:
  input: GFM # https://help.github.com/articles/about-writing-and-formatting-on-github/
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate

# Github does not allow changing
#lsi: false
#safe: true
#source: [your repo's top level directory]
#incremental: false
#highlighter: rouge
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax